# Generated by Django 4.2.2 on 2023-07-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_answer_level_question_question_answer_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
