# Generated by Django 4.2.2 on 2023-08-07 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_answer_name_remove_question_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='question_answer',
            new_name='Attemp',
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.question'),
        ),
    ]
